name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.10", "3.9", "3.10", "3.11", "3.12", "3.13"]

steps:
- uses: actions/checkout@v4
- name: setup python and say hi
  uses: actions/setup-python@v5
  with:
    python-version: '3.x'
- name: Run thing
  run: python -m runme.py
